import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Price-Wise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       

        <div>{children}</div>
      </body>
    </html>
  );
}
